  export const MEDIA = 'media'
  export const CHANNEL = 'channel'

  export const pMedia = {
    "options": [
    {"value": "", text:"Elegir media" },
    {"value": "twitch", text:"Twitch" },
    {"value": "youtube", text:"Youtube"},
    ] 
  }

export const pTwitch = {
  "options": [
  {"value": "", text:"Elegir canal" },
  {"value": "midudev", text:"midudev" },
  {"value": "danirod_", text:"danirod_"},
  {"value": "victor_robles_web", text:"victor_robles_web"}
  ] 
}


export const pYoutube = {
"options": [
    {"value": "", text:"Elegir canal" },
    {"value": "midudev", text:"midudev", 'idYT':'UC8LeXCWOalN8SxlrPcG-PaQ'},
    {"value": "midulive", text:"midulive", 'idYT':'UC3aj05GEEyzdOqYM5FLSFeg'},
    {"value": "Fazt Code", text:"Fazt Code", 'idYT':'UCMn28O1sQGochG94HdlthbA'},
    {"value": "Stanford", text:"Stanford", 'idYT':'UC-EnprmCZ3OXyAoG7vjVNCA'},
    {"value": "Juanjo Boté", text:"Juanjo Boté", 'idYT':'UC-J1aW0d3XIud9bLbnVsRfg'},
    {"value": "Instituto de Matemáticas de la UNAM", text:"Instituto de Matemáticas de la UNAM", 'idYT':'UC-_-zDEIsqM3h_jH14JzkTA'},
    {"value": "Mates Mike", text:"Mates Mike", 'idYT':'UC-_kZ3UZBsnCWJEVr8ysMww'},
    {"value": "Lemnismath", text:"Lemnismath", 'idYT':'UC-ihtKdODqNE7iPISJD3DnA'},
    {"value": "The Phantom of the Opera", text:"The Phantom of the Opera", 'idYT':'UC0HS_PILCtwqtRGOS-lftjw'},
    {"value": "Mathologer", text:"Mathologer", 'idYT':'UC1_uAIS3r8Vu6JjXWvastJg'},
    {"value": "Nekodificador", text:"Nekodificador", 'idYT':'UC1fLb1sehZn1a_ky_kmfNOg'},
    {"value": "NOVUM", text:"NOVUM", 'idYT':'UC1jTO9B2USk_rr-gbnp9IiA'},
    {"value": "Introduction to Cryptography by Christof Paar", text:"Introduction to Cryptography by Christof Paar", 'idYT':'UC1usFRN4LCMcfIV7UjHNuQg'},
    {"value": "Academatica", text:"Academatica", 'idYT':'UC2EnI_I2_SDpT_WYXEslUiw'},
    {"value": "DIEGO Broston", text:"DIEGO Broston", 'idYT':'UC2l86B-m4oibO0gTvOfFA0w'},
    {"value": "cinefilo56", text:"cinefilo56", 'idYT':'UC2sf-CAMExyKn2QrpmDrH7A'},
    {"value": "Canal USB", text:"Canal USB", 'idYT':'UC2zQI2kby8otf0OifO2K5ew'},
    {"value": "unicoos", text:"unicoos", 'idYT':'UC3RYy7GbMHDvPQGCdAh3H5g'},
    {"value": "Jaime Pavlich-Mariscal", text:"Jaime Pavlich-Mariscal", 'idYT':'UC49v89gzFw6EbVMRzLf_HQQ'},
    {"value": "Miguemáticas", text:"Miguemáticas", 'idYT':'UC4dLo2q0aUNsrHj5m6gcGlQ'},
    {"value": "Cats The Musical", text:"Cats The Musical", 'idYT':'UC4uhxfDlhySxeEQldGsn4TQ'},
    {"value": "Prof Ghrist Math", text:"Prof Ghrist Math", 'idYT':'UC5N5pRddyicAX1QJyJjIIdg'},
    {"value": "Code Java", text:"Code Java", 'idYT':'UC5ZPG2xyYIjsUIAXcCutWsQ'},
    {"value": "Jey Code", text:"Jey Code", 'idYT':'UC5xqFtQ9o3gNIGABG3s3Yyw'},
    {"value": "nptelhrd", text:"nptelhrd", 'idYT':'UC640y4UvDAlya_WOj5U4pfA'},
    {"value": "Frederic Schuller", text:"Frederic Schuller", 'idYT':'UC6SaWe7xeOp31Vo8cQG1oXw'},
    {"value": "Michael Penn", text:"Michael Penn", 'idYT':'UC6jM0RFkr4eSkzT5Gx0HOAw'},
    {"value": "Ciclos de Tiempo", text:"Ciclos de Tiempo", 'idYT':'UC76ORs9jAs7So4jlbgs4gNw'},
    {"value": "MiguelRiveraGuitar", text:"MiguelRiveraGuitar", 'idYT':'UC7MV3Kk1WiBGR2129K0BKIA'},
    {"value": "VIRTUOSSO.COM", text:"VIRTUOSSO.COM", 'idYT':'UC7mr-IT1H_avKKL7e-JqxmA'},
    {"value": "Universitat Politècnica de Catalunya - UPC", text:"Universitat Politècnica de Catalunya - UPC", 'idYT':'UC8bnBbUtFYcJVnWhsTyCCgg'},
    {"value": "freeCodeCamp.org", text:"freeCodeCamp.org", 'idYT':'UC8butISFwT-Wl7EV0hUK0BQ'},
    {"value": "MathArg", text:"MathArg", 'idYT':'UC9eZbOB2JZ00LvwPOHFEMUQ'},
    {"value": "MitoCode", text:"MitoCode", 'idYT':'UC9fAeSPVw7mAAbexCS7gPqw'},
    {"value": "This Week in PHOTO", text:"This Week in PHOTO", 'idYT':'UC9kH9c4alSSYOMWCDos8OaA'},
    {"value": "Encuentros Universitarios 3cantos", text:"Encuentros Universitarios 3cantos", 'idYT':'UC9zeNDAqdDjYULv9fyVKgSA'},
    {"value": "ChachiGuitar", text:"ChachiGuitar", 'idYT':'UCA-i40P-jwXWoTQMsxBqHBA'},
    {"value": "TED", text:"TED", 'idYT':'UCAuUUnT6oDeKwE6v1NGQxug'},
    {"value": "Chili World", text:"Chili World", 'idYT':'UCBGzm7haKhfUdBBREbGMfIA'},
    {"value": "Udacity", text:"Udacity", 'idYT':'UCBVCi5JbYmfG3q5MEuoWdOw'},
    {"value": "Moldeo Interactive", text:"Moldeo Interactive", 'idYT':'UCBnFwsPRlWD3iDcoJwBiHzA'},
    {"value": "Sigma Coding", text:"Sigma Coding", 'idYT':'UCBsTB02yO0QGwtlfiv5m25Q'},
    {"value": "MathMajor", text:"MathMajor", 'idYT':'UCC6Wl-xnWVS9FP0k-Hj5aiw'},
    {"value": "LoremaryluGT", text:"LoremaryluGT", 'idYT':'UCCghLN5D_ztxvny_U8pgI3g'},
    {"value": "PROA (Preparación para Olimpiadas de Astronomía)", text:"PROA (Preparación para Olimpiadas de Astronomía)", 'idYT':'UCCsB6J6Y_nxu8Z5NUOytmgw'},
    {"value": "Fermilab", text:"Fermilab", 'idYT':'UCD5B6VoXv41fJ-IW8Wrhz9A'},
    {"value": "MIT OpenCourseWare", text:"MIT OpenCourseWare", 'idYT':'UCEBb1b_L6zDS3xTUrIALZOw'},
    {"value": "iDESWEB UA", text:"iDESWEB UA", 'idYT':'UCESqCI84cpFhrs6Ctn7Dzhg'},
    {"value": "Astro Sabadell", text:"Astro Sabadell", 'idYT':'UCFBgr9L5Gi0a-UxezWdckqg'},
    {"value": "JandroCode", text:"JandroCode", 'idYT':'UCFJ4v7lzWKJ-hG4qXmbZxPg'},
    {"value": "Andrey K", text:"Andrey K", 'idYT':'UCFJyaHVyWKb2y-HkIAEPIdA'},
    {"value": "Faculty of Khan", text:"Faculty of Khan", 'idYT':'UCGDanWUzNMbIV11lcNi-yBg'},
    {"value": "Derivando", text:"Derivando", 'idYT':'UCH-Z8ya93m7_RD02WsCSZYA'},
    {"value": "Jesus Christ Superstar", text:"Jesus Christ Superstar", 'idYT':'UCH-uFQkWx9tYjM-XDtK6PKQ'},
    {"value": "Bluuweb", text:"Bluuweb", 'idYT':'UCH7IANkyEcsVW_y1IlpkamQ'},
    {"value": "MateFacil", text:"MateFacil", 'idYT':'UCHwtud9tX_26eNKyZVoKfjA'},
    {"value": "Sigma Documentaries", text:"Sigma Documentaries", 'idYT':'UCI539iFJ-GY-z_wTcVZMbMw'},
    {"value": "Physics Explained", text:"Physics Explained", 'idYT':'UCIZ5ZOeiXYbmKTl_85ghNPw'},
    {"value": "Daniel López", text:"Daniel López", 'idYT':'UCIthnyAWcQ8yNIXY9sHDeNQ'},
    {"value": "Physics Videos by Eugene Khutoryansky", text:"Physics Videos by Eugene Khutoryansky", 'idYT':'UCJ0yBou72Lz9fqeMXh9mkog'},
    {"value": "Jackie Wang", text:"Jackie Wang", 'idYT':'UCJZYwBUBWvMxBStBMaG1shQ'},
    {"value": "Wolfram", text:"Wolfram", 'idYT':'UCJekgf6k62CQHdENWf2NgAQ'},
    {"value": "GuitarJamz", text:"GuitarJamz", 'idYT':'UCJgRMHrtQpnhKHdsGiFQRyQ'},
    {"value": "FalconMasters", text:"FalconMasters", 'idYT':'UCJl1YajcPWTeJNsQhGyMIMg'},
    {"value": "Algebra y Matematica Discreta", text:"Algebra y Matematica Discreta", 'idYT':'UCJqqRbrAcEd0PiVy91ZiGrw'},
    {"value": "BroadwayWorld Spain - musicales y teatro musical", text:"BroadwayWorld Spain - musicales y teatro musical", 'idYT':'UCJyQMRRngzbWzW7e8gCIu0Q'},
    {"value": "Mauro De Maria", text:"Mauro De Maria", 'idYT':'UCKmBzsQRqNwxBIb2Awcaoqw'},
    {"value": "alcatri", text:"alcatri", 'idYT':'UCL_I6VT5RaRinR6TgXdht0A'},
    {"value": "NullSafe Architect", text:"NullSafe Architect", 'idYT':'UCLek8zeRbg3gm5usDe6YFzw'},
    {"value": "Humberto Aguilar", text:"Humberto Aguilar", 'idYT':'UCMU61AdtSvdPPca2feG_JyQ'},
    {"value": "Excel Avanzado para Administración de Empresas", text:"Excel Avanzado para Administración de Empresas", 'idYT':'UCMUecQg368GFojNXAQ5P8Qg'},
    {"value": "MinutoDeFísica", text:"MinutoDeFísica", 'idYT':'UCMnPZh6PyA5PSYoNt0cjuxg'},
    {"value": "Brant Carlson", text:"Brant Carlson", 'idYT':'UCNIEAv633WRg4ubBIhOcwMg'},
    {"value": "Universidad Miguel Hernández de Elche", text:"Universidad Miguel Hernández de Elche", 'idYT':'UCNJuVlIFM_9cOGwooLMjijQ'},
    {"value": "Susskind Lectures", text:"Susskind Lectures", 'idYT':'UCNPslw9h5x5OqEBUX65DEmg'},
    {"value": "UPM", text:"UPM", 'idYT':'UCNW9djX3St9Wtb-oAsSEtkQ'},
    {"value": "LAFF Linear Algebra - Foundations to Frontiers (www.ulaff.net)", text:"LAFF Linear Algebra - Foundations to Frontiers (www.ulaff.net)", 'idYT':'UCNjDr_OW6Hb2lnHi-XqJNJg'},
    {"value": "Vida MRR - Programacion web", text:"Vida MRR - Programacion web", 'idYT':'UCOD6LXgeBoeiUZTsPLdG-0g'},
    {"value": "ACADEMIA MUNDO DE LA MÚSICA", text:"ACADEMIA MUNDO DE LA MÚSICA", 'idYT':'UCOE1O6jBJ_LWCHzAVEIaXRw'},
    {"value": "Learning Programming", text:"Learning Programming", 'idYT':'UCPSDAF3Htm3AIxw4OUM3Lew'},
    {"value": "Rousseau", text:"Rousseau", 'idYT':'UCPZUQqtVDmcjm4NY5FkzqLA'},
    {"value": "Kassia", text:"Kassia", 'idYT':'UCPmCaKjzYF3pXYLfaRhacwA'},
    {"value": "Astrocity.es", text:"Astrocity.es", 'idYT':'UCQ-_45PTOmE3ukoWHvmmjoA'},
    {"value": "Especialistas En Excel", text:"Especialistas En Excel", 'idYT':'UCQB_n4jadSoo7Gs-aj3miSA'},
    {"value": "Manuel González", text:"Manuel González", 'idYT':'UCQLWbxZbgftDIhw21i6q_OA'},
    {"value": "Date un Vlog", text:"Date un Vlog", 'idYT':'UCQX_MZRCaluNKxkywkLEgfA'},
    {"value": "3Blue1Brown Español", text:"3Blue1Brown Español", 'idYT':'UCQbsk1JQNaskUlfdoyiWJDg'},
    {"value": "Disney UK", text:"Disney UK", 'idYT':'UCQphRgAhj5UxktrQNP3WF5g'},
    {"value": "Natural Portraits", text:"Natural Portraits", 'idYT':'UCQrYBVmH3Gz9IO5ryXIGhdw'},
    {"value": "makigas: aprende a programar", text:"makigas: aprende a programar", 'idYT':'UCQufRmIMRTLdRxTsXCh4-5w'},
    {"value": "Lino Patalano", text:"Lino Patalano", 'idYT':'UCRalmEd5WekrMO0B6n-rqwA'},
    {"value": "Boyer PLC", text:"Boyer PLC", 'idYT':'UCRba1gA9ADvC7rZTSfK67vQ'},
    {"value": "Excel Hecho Fácil", text:"Excel Hecho Fácil", 'idYT':'UCS9GODhqnNOpMjuZp5TIKfA'},
    {"value": "poramoralafisica", text:"poramoralafisica", 'idYT':'UCSBZ3TCrfOd4Pcg8wZcwhDQ'},
    {"value": "Coffee Break Podcast", text:"Coffee Break Podcast", 'idYT':'UCSM_GE9SI6hlPauLfG6Dkuw'},
    {"value": "BettaTech", text:"BettaTech", 'idYT':'UCSf6S_PAhXsqGMTPDiKgdRg'},
    {"value": "EL TERRAT", text:"EL TERRAT", 'idYT':'UCShuVWEZ2KhSb2kAYd7-StQ'},
    {"value": "aster aster", text:"aster aster", 'idYT':'UCSsye26iuHOwrOuFoeIafvA'},
    {"value": "Ger Garpe", text:"Ger Garpe", 'idYT':'UCU9cnhGC8CCOKUJTkuqeIzw'},
    {"value": "Live Aid", text:"Live Aid", 'idYT':'UCUAVzSGkkTa-IoMx_x1XK4Q'},
    {"value": "Centre Cívic Guinardó", text:"Centre Cívic Guinardó", 'idYT':'UCUbn_JmLMFbOhcmBeQNiqqg'},
    {"value": "ACDSee", text:"ACDSee", 'idYT':'UCUtJDEqnEm2gYN5tIWbHokQ'},
    {"value": "Programación Desde Cero", text:"Programación Desde Cero", 'idYT':'UCVBUKfDOcDMaxybQ0Ntk1Ww'},
    {"value": "MrYouMath", text:"MrYouMath", 'idYT':'UCVdkYJ5CcDPKzlSqbxw52vA'},
    {"value": "Physics Explained", text:"Physics Explained", 'idYT':'UCVxIDFY01y4n_c2lK1TB-KA'},
    {"value": "Kids&Us language school", text:"Kids&Us language school", 'idYT':'UCWBldQ_b1Z4oBQHJrtojgbg'},
    {"value": "Foto K Canal Video", text:"Foto K Canal Video", 'idYT':'UCWCW6OwvHs8OxL_p_FeH6GQ'},
    {"value": "Fazt", text:"Fazt", 'idYT':'UCX9NJ471o7Wie1DQe94RVIg'},
    {"value": "MrExcel.com", text:"MrExcel.com", 'idYT':'UCXbicpVq_ALWG4ijPKsR7ZQ'},
    {"value": "guitarraviva", text:"guitarraviva", 'idYT':'UCXm0v3a9g17bSATE-DMMxRg'},
    {"value": "Veritasium en español", text:"Veritasium en español", 'idYT':'UCXtxgWwk55kVJo9lCCZRdmg'},
    {"value": "3Blue1Brown", text:"3Blue1Brown", 'idYT':'UCYO_jab_esuFRV4b17AJtAw'},
    {"value": "Javier Garcia", text:"Javier Garcia", 'idYT':'UCYOv9HwOFwK0lY2dUQlZSpg'},
    {"value": "clipset", text:"clipset", 'idYT':'UCYkoAtIMi6oFG_8SO5YrauQ'},
    {"value": "Sergio Alejandro Campos - EXCELeINFO", text:"Sergio Alejandro Campos - EXCELeINFO", 'idYT':'UCZHYfToa95Ybj3vPN9EPMAg'},
    {"value": "todoMUSICALES", text:"todoMUSICALES", 'idYT':'UCZP5zlmTFxrjtbv7OUBNIog'},
    {"value": "BBC Music", text:"BBC Music", 'idYT':'UCZtDUmC3W7j25XHZWFT_XgQ'},
    {"value": "JavaTechnoLessons", text:"JavaTechnoLessons", 'idYT':'UC_KLrbvmPq7NztsJvs1aoIQ'},
    {"value": "blackpenredpen", text:"blackpenredpen", 'idYT':'UC_SvYP0k05UKiJ_2ndB02IA'},
    {"value": "Hum ol", text:"Hum ol", 'idYT':'UC_giUEHRh5dxk3jm7kdVrLA'},
    {"value": "Google Developers", text:"Google Developers", 'idYT':'UC_x5XG1OV2P6uZZ5FSM9Ttw'},
    {"value": "Jaime Altozano", text:"Jaime Altozano", 'idYT':'UCa3DVlGH2_QhvwuWlPa6MDQ'},
    {"value": "El Traductor de Ingeniería", text:"El Traductor de Ingeniería", 'idYT':'UCa6V1UVOXN4wDm7RDQDoa6g'},
    {"value": "El Robot de Platón", text:"El Robot de Platón", 'idYT':'UCaVPhFg-Ax873wvhbNitsrQ'},
    {"value": "La Ruina", text:"La Ruina", 'idYT':'UCaw0csDOShCAEaC8S5ItIIQ'},
    {"value": "Stanford Physics", text:"Stanford Physics", 'idYT':'UCbC1OVNVljMnQI0TRatrHLw'},
    {"value": "QuantumFracture", text:"QuantumFracture", 'idYT':'UCbdSYaPD-lr1kW27UJuk8Pw'},
    {"value": "Jesús Conde", text:"Jesús Conde", 'idYT':'UCbr0g_ADLsdzhcoAFUZkuug'},
    {"value": "FAAE", text:"FAAE", 'idYT':'UCd0wCW9cOB9V_UTKOtc2yhw'},
    {"value": "COPÉRNICO HUBBLE", text:"COPÉRNICO HUBBLE", 'idYT':'UCdaa9_RxtxJ-WRcvT6DM6TA'},
    {"value": "pildorasinformaticas", text:"pildorasinformaticas", 'idYT':'UCdulIs-x_xrRd1ezwJZR9ww'},
    {"value": "MateFacil - Física", text:"MateFacil - Física", 'idYT':'UCeFNpG-n8diSNszUAKaqM_A'},
    {"value": "Ciencia para Nes", text:"Ciencia para Nes", 'idYT':'UCehRFqXC_uXY4308-sKMxKA'},
    {"value": "Excel y Más", text:"Excel y Más", 'idYT':'UCfFT6jJx6khLYjibRwKODhA'},
    {"value": "Domingo Mery", text:"Domingo Mery", 'idYT':'UCfiFiJBkLdzRq1hIPRMfvpQ'},
    {"value": "efrain vega", text:"efrain vega", 'idYT':'UCfm6O7qvsyOlY6HyXHRy8Bw'},
    {"value": "SonGt Vlog", text:"SonGt Vlog", 'idYT':'UCft8eUU0ZjczlD4pKhmYQRg'},
    {"value": "Neural Activity", text:"Neural Activity", 'idYT':'UCg-SQGXhqm_8tfACFgmKgPQ'},
    {"value": "Barcelona Memory", text:"Barcelona Memory", 'idYT':'UCg6Ob_Feu2_QRUAFkYl0ZkQ'},
    {"value": "Inventors", text:"Inventors", 'idYT':'UCgBmdSqK9yv5oY3xU4xXAXw'},
    {"value": "José Pablo Alvarado Moya", text:"José Pablo Alvarado Moya", 'idYT':'UCgErKJiMbKs4xFrLHF0EIuA'},
    {"value": "ladomicilio", text:"ladomicilio", 'idYT':'UCg_OlcixgDSyw9334azDOVA'},
    {"value": "4 Go Academy", text:"4 Go Academy", 'idYT':'UCgnJhjkoMhkv9vxzAHqa1vA'},
    {"value": "Leifer Mendez", text:"Leifer Mendez", 'idYT':'UCgrIGp5QAnC0J8LfNJxDRDw'},
    {"value": "laSexta", text:"laSexta", 'idYT':'UCh1OgMIWOlDBhFEYL3DHWjQ'},
    {"value": "Agrupación Astronómica de Madrid", text:"Agrupación Astronómica de Madrid", 'idYT':'UCh68r8UFbFSVKN0SmVHE8vA'},
    {"value": "Microsoft Excel a Todo Nivel", text:"Microsoft Excel a Todo Nivel", 'idYT':'UCh7H5QEvSVPmzwGBI_y8jBA'},
    {"value": "Tú, Yo, Excel y Power BI", text:"Tú, Yo, Excel y Power BI", 'idYT':'UChJuckpv2YohJfUl1wboa4w'},
    {"value": "ExactasUBAoficial", text:"ExactasUBAoficial", 'idYT':'UChufJxPKL814SemB0py3QhQ'},
    {"value": "Lectures by Walter Lewin. They will make you ♥ Physics.", text:"Lectures by Walter Lewin. They will make you ♥ Physics.", 'idYT':'UCiEHVhv0SBMpP75JbzJShqw'},
    {"value": "Queen Official", text:"Queen Official", 'idYT':'UCiMhD4jzUqG-IgPzUmmytRQ'},
    {"value": "Ciencias Para Todo", text:"Ciencias Para Todo", 'idYT':'UCijeV9aEWlyQm-YlcecSIcg'},
    {"value": "cuerdabierta", text:"cuerdabierta", 'idYT':'UCiqi1yE7dHtjRLey3u8InNg'},
    {"value": "Gerónimo Rauch", text:"Gerónimo Rauch", 'idYT':'UCisGM2XDG9YmQiOe3xQ0Y8A'},
    {"value": "Stanford Institute for Theoretical Physics", text:"Stanford Institute for Theoretical Physics", 'idYT':'UCj2PBh1npuzyQ52qqV9eAmQ'},
    {"value": "Office Systems", text:"Office Systems", 'idYT':'UCjmA1bV7BD-wrEf8DT1jOpQ'},
    {"value": "Instituto de Física Teórica IFT", text:"Instituto de Física Teórica IFT", 'idYT':'UCk195x4zYdMx4LhqEwhcPng'},
    {"value": "Taylor Davis", text:"Taylor Davis", 'idYT':'UCk40qSGYnVdFFBNXRjrvdpQ'},
    {"value": "UNED Cursos", text:"UNED Cursos", 'idYT':'UCknxBBpBH7CtlEk5cbspOcA'},
    {"value": "Closer To Truth", text:"Closer To Truth", 'idYT':'UCl9StMQ79LtEvlrskzjoYbQ'},
    {"value": "MathPures", text:"MathPures", 'idYT':'UClTPdtlgYcJp7f4WXxEnWcw'},
    {"value": "YouTube Movies", text:"YouTube Movies", 'idYT':'UClgRkhTL3_hImCAmdLfDE4g'},
    {"value": "For the Allure of Physics", text:"For the Allure of Physics", 'idYT':'UCliSRiiRVQuDfgxI_QN_Fmw'},
    {"value": "TVE English", text:"TVE English", 'idYT':'UCm2zc4q_XXAxR9HCA_06X_Q'},
    {"value": "UOC - Universitat Oberta de Catalunya", text:"UOC - Universitat Oberta de Catalunya", 'idYT':'UCm3FGJTmlb30B71183Pza4A'},
    {"value": "Germán Fernández", text:"Germán Fernández", 'idYT':'UCnB0Y3Y2CDlO76g691nMIbA'},
    {"value": "Parker Photographic", text:"Parker Photographic", 'idYT':'UCnSAUHBwdAEPWeeIs8LTViA'},
    {"value": "Luigi Code", text:"Luigi Code", 'idYT':'UCn_o9NxxyuET2G9Ek4wyRZA'},
    {"value": "Develoteca", text:"Develoteca", 'idYT':'UCne4X8czEkhh8GPRjXBIQJw'},
    {"value": "GIMP TUT", text:"GIMP TUT", 'idYT':'UCnu0Is2tlSmeoIKKXUyZIqw'},
    {"value": "Mu Prime Math", text:"Mu Prime Math", 'idYT':'UCo8T0D8my1Hz5KoHCRYOAnQ'},
    {"value": "Tomas Ruiz Diaz", text:"Tomas Ruiz Diaz", 'idYT':'UCp6InR7pL3lJMFDHuq9mXtA'},
    {"value": "Marco Regalia", text:"Marco Regalia", 'idYT':'UCpxFvQuvEuI8JEuLmmCZO8Q'},
    {"value": "CSIC Eventos", text:"CSIC Eventos", 'idYT':'UCqGHVsG_BPiLCs8mZDby5dg'},
    {"value": "ASTER", text:"ASTER", 'idYT':'UCqWQWvgGAw-3fxuKpNWuStA'},
    {"value": "Clever Programmer", text:"Clever Programmer", 'idYT':'UCqrILQNl5Ed9Dz6CGMyvMTQ'},
    {"value": "MathTheBeautiful", text:"MathTheBeautiful", 'idYT':'UCr22xikWUK2yUW4YxOKXclQ'},
    {"value": "CourseraVideos", text:"CourseraVideos", 'idYT':'UCrHRncSm4F4u_DE9rQAvdug'},
    {"value": "Sarah Brightman", text:"Sarah Brightman", 'idYT':'UCriL6-sBup_Tis7trjOALnw'},
    {"value": "Universitat Politècnica de València - UPV", text:"Universitat Politècnica de València - UPV", 'idYT':'UCsANOtTfEeqqFMkyRnfCnOQ'},
    {"value": "AAVSO HQ", text:"AAVSO HQ", 'idYT':'UCsAmXgodtwToO-pY9A6NpMQ'},
    {"value": "Javier Muñiz", text:"Javier Muñiz", 'idYT':'UCt4oJu2ItngyTNBwPNmJDfA'},
    {"value": "Flammable Maths", text:"Flammable Maths", 'idYT':'UCtAIs1VCQrymlAnw3mGonhw'},
    {"value": "DarkSide | Alex Alvarez", text:"DarkSide | Alex Alvarez", 'idYT':'UCta23vraQgDPpIuB9D8XTaA'},
    {"value": "Mentalidad De Ingeniería", text:"Mentalidad De Ingeniería", 'idYT':'UCtfhmY_sWRukJl5CAgsqV0A'},
    {"value": "lasmatematicas.es", text:"lasmatematicas.es", 'idYT':'UCtkmpuSfYi9R8Xeq9OrO6GA'},
    {"value": "Tecnologias Disruptivas", text:"Tecnologias Disruptivas", 'idYT':'UCtr7bbfZ0F7d2_3cVIi52jQ'},
    {"value": "valemusic", text:"valemusic", 'idYT':'UCuABtq2JQXrI-TffLVoK2uA'},
    {"value": "Pedro Joya", text:"Pedro Joya", 'idYT':'UCuCIDfYuJFHd9oCcJZ0xl_Q'},
    {"value": "Fernando Herrera", text:"Fernando Herrera", 'idYT':'UCuaPTYj15JSkETGnEseaFFg'},
    {"value": "Victor Robles WEB", text:"Victor Robles WEB", 'idYT':'UCv85NiROLKddHa0fBATwTzw'},
    {"value": "Sixty Symbols", text:"Sixty Symbols", 'idYT':'UCvBqzzvUBLCs8Y7Axb-jZew'},
    {"value": "Cesar Antonio Izquierdo Merlo", text:"Cesar Antonio Izquierdo Merlo", 'idYT':'UCvThY8eyKOnPxhJquurcW1Q'},
    {"value": "Excel Free Blog - Power Platform", text:"Excel Free Blog - Power Platform", 'idYT':'UCvfxanLbaBE3QxZr-PU5vyQ'},
    {"value": "UNL Astronomy", text:"UNL Astronomy", 'idYT':'UCw5d1S08MW2fqCdiJyfE8yw'},
    {"value": "Derek Banas", text:"Derek Banas", 'idYT':'UCwRXb5dUK4cvsHbx-rGzSgw'},
    {"value": "jmreales57", text:"jmreales57", 'idYT':'UCwYFpbB_pFoI5qY7yOwX9qQ'},
    {"value": "ViaScience", text:"ViaScience", 'idYT':'UCx6G76LCKLdd7__F0xt5POQ'},
    {"value": "MoureDev by Brais Moure", text:"MoureDev by Brais Moure", 'idYT':'UCxPD7bsocoAMq8Dj18kmGyQ'},
    {"value": "John Ortiz Ordoñez", text:"John Ortiz Ordoñez", 'idYT':'UCxS-DE8WX3-2_ExdZO2HFww'},
    {"value": "Escuela Superior Politécnica del Litoral", text:"Escuela Superior Politécnica del Litoral", 'idYT':'UCxWAiJzpSMZ5EHELK0GI71w'},
    {"value": "Dot CSV", text:"Dot CSV", 'idYT':'UCy5znSnfMsDwaLlROnZ7Qbg'},
    {"value": "Lindsey Stirling", text:"Lindsey Stirling", 'idYT':'UCyC_4jvPzLiSkJkLIkA7B8g'},
    {"value": "CursosDesarrolloWeb", text:"CursosDesarrolloWeb", 'idYT':'UCylETmSOiHASVVfpxQY8KVA'},
    {"value": "Alvaro Chirou", text:"Alvaro Chirou", 'idYT':'UCytDb_y2N7ZFqsgP2pNKOXQ'},
    {"value": "Fisica y algo mas", text:"Fisica y algo mas", 'idYT':'UCyz2HPm9zbycV2J1rPfVTFg'},
    {"value": "Excel y Finanzas", text:"Excel y Finanzas", 'idYT':'UCzn2BOxJnPVAaNPjRnkQktQ'},
] 
}